import {Country, Genre} from "../global.types.ts";

export interface FilmInfo {
    kinopoiskId?: number;
    kinopoiskHDId?: string;
    imdbId?: string;
    nameRu?: string;
    nameEn?: string | null;
    nameOriginal?: string;
    posterUrl?: string;
    posterUrlPreview?: string;
    coverUrl?: string | null;
    logoUrl?: string | null;
    reviewsCount?: number;
    ratingGoodReview?: number | null;
    ratingGoodReviewVoteCount?: number;
    ratingKinopoisk?: number | null;
    ratingKinopoiskVoteCount?: number;
    ratingImdb?: number | null;
    ratingImdbVoteCount?: number;
    ratingFilmCritics?: number | null;
    ratingFilmCriticsVoteCount?: number;
    ratingAwait?: number | null;
    ratingAwaitCount?: number;
    ratingRfCritics?: number | null;
    ratingRfCriticsVoteCount?: number;
    webUrl?: string;
    year?: number;
    filmLength?: number | null;
    slogan?: string | null;
    description?: string | null;
    shortDescription?: string | null;
    editorAnnotation?: string | null;
    isTicketsAvailable?: boolean;
    productionStatus?: string | null;
    type?: string;
    ratingMpaa?: string | null;
    ratingAgeLimits?: string | null;
    countries?: Country[];
    genres?: Genre[];
    startYear?: number | null;
    endYear?: number | null;
    serial?: boolean;
    shortFilm?: boolean;
    completed?: boolean;
    hasImax?: boolean;
    has3D?: boolean;
    lastSync?: string;
}
